---
title: "SAM vs Stunting Analysis"
author: Monica N Mweetwa
date: 14/08/2024
---
Set working directory
```{r setup}
   #knitr::opts_knit$set(root.dir = normalizePath("~/Dropbox/BEECH_16s_Analysis")) 
   knitr::opts_knit$set(root.dir = normalizePath("C:/Users/Monica/Dropbox/BEECH_16s_Analysis")) 
```

load data
```{r}
load("Data/RData/phyloseq_dataset_species.RData") #ps0
library(phyloseq)
library(ggpubr)
library("ggplot2")
library(tableone)
library(tidyverse)
library(microViz)
library(pals) #for color palette
```

#1. Relative Abundance
```{r}
otu_palette <- c(unname(alphabet2(n=15)), "lightgray")

a <- ps0 %>%
  tax_fix() %>% 
  comp_barplot(tax_level = "Genus",
               label = "PID",
               n_taxa = 15) +
  coord_flip() +
  facet_grid(
    rows = vars(mal.type),
    scales = "free_y", # this only frees y scale per row in grid faceting
    space = "free_y" # allows bars to be same size by freeing facet heights
  ) +
  theme(axis.text.y = (element_blank()),
        axis.ticks.y = (element_blank()))

ggsave("Output/Combined/RelAbund/RelAbund_gen.png", plot = a, dpi = 600, device = "png", width = 8, height = 8, units = "in")

#get relative abundance
ps0_gen <- ps0 %>% 
  tax_fix() %>%
  tax_transform("compositional", rank = "Genus") %>%
  ps_melt() %>%
  group_by(mal.type, OTU) %>%
  summarize(N = n(),
            mean_val = round((mean(Abundance, na.rm = T))*100,5),
            SD_val = round((sd(Abundance, na.rm = T))*100,5)) 
write_csv(ps0_gen, "Output/Combined/RelAbund/Gen_abund.csv")

#Phylum data

a2 <- ps0 %>%
  tax_fix() %>% 
  comp_barplot(tax_level = "Phylum",
               label = "PID",
               n_taxa = 15) +
  coord_flip() +
  facet_grid(
    rows = vars(mal.type),
    scales = "free_y", # this only frees y scale per row in grid faceting
    space = "free_y" # allows bars to be same size by freeing facet heights
  ) +
  theme(axis.text.y = (element_blank()),
        axis.ticks.y = (element_blank()))

ggsave("Output/Combined/RelAbund/RelAbund_phy.png", plot = a2, dpi = 600, device = "png", width = 8, height = 8, units = "in")

#get relative abundance
ps0_phy <- ps0 %>% 
  tax_fix() %>%
  tax_transform("compositional", rank = "Phylum") %>%
  ps_melt() %>%
  group_by(mal.type, OTU) %>%
  summarize(N = n(),
            mean_val = round((mean(Abundance, na.rm = T))*100,5),
            SD_val = round((sd(Abundance, na.rm = T))*100,5)) 
write_csv(ps0_phy, "Output/Combined/RelAbund/Phy_abund.csv")

library(MicrobiomeStat)
#convert to microbiomestat object
count_tab <- as.data.frame(t(ps0@otu_table))
count_tab <- count_tab %>%  as.matrix()
tax_tab <- as.data.frame(ps0@tax_table)
tax_tab <- tax_tab %>%  as.matrix()
met_tab <- ps0@sam_data
met_tab2 <- as.data.frame(met_tab@.Data)
rownames(met_tab2) <- met_tab@row.names
colnames(met_tab2) <- met_tab@names

dat_mcbst <- list(
  feature.tab = count_tab,
  meta.dat = met_tab2,
  feature.ann = tax_tab
)
#barplot
barpplots <- generate_taxa_barplot_single(
  data.obj = dat_mcbst,
  subject.var = "PID",
  time.var = NULL,
  t.level = NULL,
  group.var = "mal.type",
  feature.level = "Genus",
  feature.dat.type = "count",
  feature.number = 30,
  base.size = 10,
  theme.choice = "bw",
  custom.theme = NULL,
  palette = NULL,
  pdf = F)
ggsave("Output/Combined/RelAbund/RelAbund_gen_avg.png", plot = barpplots[["Genus"]][["average"]], dpi = 600, device = "png", width = 16, height = 8, units = "in")

```

#2. Alpha diversity
```{r}
divIdx = c("Observed", "Chao1", "Shannon", "Simpson")
ad = estimate_richness(ps0, measures = "Shannon")
ad <- rownames_to_column(ad, "SampleID")
#ad$SampleID <- str_replace( ad$SampleID, "[X]", "")
#ad$SampleID <- str_replace( ad$SampleID, "[.]", "-")

##add the pd estimate too
library(btools)
pd <- estimate_pd(ps0)
pd <- rownames_to_column(pd, "SampleID")

AlphaDiv = merge(pd, ad, by = "SampleID")

add <- data.frame(sample_data(ps0))
add <- rownames_to_column(add, "SampleID2")

add2 = merge(add, AlphaDiv, by = "SampleID")

colors = c("SAM" = "#336633", "Stunting" = "#CC6600")
my_comparisons = list(c("SAM", "Stunting"))
b <- ggplot(add2, aes(mal.type, PD, fill = mal.type)) + 
  geom_boxplot( outlier.shape = NA, size = 0.8, width = 0.8, na.rm = TRUE) +
  theme_bw() + 
  scale_fill_manual(values = colors) +
  stat_compare_means() +
  labs(x = " ", 
       y = "Faith's PD")  +
  theme(axis.text.x = element_text(vjust = 0.5),
        plot.title = element_text(size = 25, hjust = 0.5),
        legend.position = "none")
ggsave("Output/Combined/AlphaDiv/AlphaDiv.png", plot = b, dpi = 600, device = "png", width = 4, height = 4, units = "in")
```

linear regression on alpha diversity
```{r}
#regression function
library(lm.beta)
lm_uni_func = function(equation,data,class2){
  require(lm.beta)
  data2 <- data %>% filter(mal.type == class2)
  lm_mod = lm(formula = equation, data = data2) #family must be binomial if y-values are between 0 & 1
  lm_mod_st <- lm.beta(lm_mod)
  mod <- summary(lm_mod_st)
  coef = as.data.frame(mod[["coefficients"]])
  coef <- coef %>%
    mutate(lwr=Estimate-1.96*`Std. Error`,
           upr=Estimate+1.96*`Std. Error`,
           `95% CI` = paste0("(",format(lwr,scientific = T),", ",format(upr,scientific = T),")"),
           Number_of_observations = paste0(nobs(lm_mod))) %>%
    rownames_to_column(var = "Term") %>%
    select(-lwr, -upr)%>%
    filter(Term != "(Intercept)")
  print(coef)
}

#univariable regression analysis - stunting group
lm_age <- lm_uni_func(equation = PD ~ AgeMonths_endo, data = add2, class2 = "Stunting")
lm_sex <- lm_uni_func(equation = PD ~ Sex, data = add2, class2 = "Stunting")
lm_hiv <-lm_uni_func(equation = PD ~ hiv_char, data = add2, class2 = "Stunting")
lm_waz <-lm_uni_func(equation = PD ~ WAZ_endo, data = add2, class2 = "Stunting")
lm_whz <- lm_uni_func(equation = PD ~ WHZ_endo, data = add2, class2 = "Stunting")
lm_laz <- lm_uni_func(equation = PD ~ LAZ_endo, data = add2, class2 = "Stunting")
lm_glp2 <- lm_uni_func(equation = PD ~ GLP.2_endo, data = add2, class2 = "Stunting")
lm_fabp <- lm_uni_func(equation = PD ~ I.FABP_endo, data = add2, class2 = "Stunting")
lm_lps <- lm_uni_func(equation = PD ~ LPS_endo, data = add2, class2 = "Stunting")
lm_lbp<- lm_uni_func(equation = PD ~ LBP_new, data = add2, class2 = "Stunting")
lm_scd14 <- lm_uni_func(equation = PD ~ sCD14_endo, data = add2, class2 = "Stunting")
lm_vh <- lm_uni_func(equation = PD ~ VH, data = add2, class2 = "Stunting")
lm_cd <- lm_uni_func(equation = PD ~ CD, data = add2, class2 = "Stunting")
lm_esa <- lm_uni_func(equation = PD ~ ESA, data = add2, class2 = "Stunting")
lm_gast <- lm_uni_func(equation = PD ~ GastricPh_endo, data = add2, class2 = "Stunting")

reg_stats <- Reduce(function(x,y) merge(x, y, all.x = TRUE, all.y = TRUE),
       list(lm_age, lm_sex, lm_hiv, lm_waz, lm_whz, lm_laz, lm_glp2, lm_fabp, lm_lps, lm_lbp, lm_scd14, lm_vh, lm_cd, lm_esa, lm_gast))
write.csv(reg_stats, "Output/Combined/AlphaDiv/Alpha_uni_reg_stunting.csv")
rm(list = ls()[grep("^lm", ls())])

#univariable regression analysis - SAM group
lm_uni_func = function(equation,data,class2){
  require(lm.beta)
  data2 <- data %>% filter(mal.type == class2)
  lm_mod = lm(formula = equation, data = data2) #family must be binomial if y-values are between 0 & 1
  lm_mod_st <- lm.beta(lm_mod)
  mod <- summary(lm_mod_st)
  coef = as.data.frame(mod[["coefficients"]])
  coef <- coef %>%
    mutate(lwr=Estimate-1.96*`Std. Error`,
           upr=Estimate+1.96*`Std. Error`,
           `95% CI` = paste0("(",format(lwr,scientific = T),", ",format(upr,scientific = T),")"),
           Number_of_observations = paste0(nobs(lm_mod))) %>%
    rownames_to_column(var = "Term") %>%
    select(-lwr, -upr)%>%
    filter(Term != "(Intercept)")
  print(coef)
}
lm_age <- lm_uni_func(equation = PD ~ AgeMonths_endo, data = add2, class2 = "SAM")
lm_sex <- lm_uni_func(equation = PD ~ Sex, data = add2, class2 = "SAM")
lm_hiv <-lm_uni_func(equation = PD ~ hiv_char, data = add2, class2 = "SAM")
lm_waz <-lm_uni_func(equation = PD ~ WAZ_endo, data = add2, class2 = "SAM")
lm_whz <- lm_uni_func(equation = PD ~ WHZ_endo, data = add2, class2 = "SAM")
lm_laz <- lm_uni_func(equation = PD ~ LAZ_endo, data = add2, class2 = "SAM")
lm_glp2 <- lm_uni_func(equation = PD ~ GLP.2_endo, data = add2, class2 = "SAM")
lm_fabp <- lm_uni_func(equation = PD ~ I.FABP_endo, data = add2, class2 = "SAM")
lm_lps <- lm_uni_func(equation = PD ~ LPS_endo, data = add2, class2 = "SAM")
lm_lbp<- lm_uni_func(equation = PD ~ LBP_new, data = add2, class2 = "SAM")
lm_scd14 <- lm_uni_func(equation = PD ~ sCD14_endo, data = add2, class2 = "SAM")
lm_vh <- lm_uni_func(equation = PD ~ VH, data = add2, class2 = "SAM")
lm_cd <- lm_uni_func(equation = PD ~ CD, data = add2, class2 = "SAM")
lm_esa <- lm_uni_func(equation = PD ~ ESA, data = add2, class2 = "SAM")
lm_gast <- lm_uni_func(equation = PD ~ GastricPh_endo, data = add2, class2 = "SAM")

reg_stats <- Reduce(function(x,y) merge(x, y, all.x = TRUE, all.y = TRUE),
       list(lm_age, lm_sex, lm_hiv, lm_waz, lm_whz, lm_laz, lm_glp2, lm_fabp, lm_lps, lm_lbp, lm_scd14, lm_vh, lm_cd, lm_esa, lm_gast))
write.csv(reg_stats, "Output/Combined/AlphaDiv/Alpha_uni_reg_SAM.csv")
rm(list = ls()[grep("^lm", ls())])

```

3. Beta diversity
```{r}
permanova_func = function(equation,data){
  dist = phyloseq::distance(data, method="bray")
  metadata <- data.frame(sample_data(data))
  require(vegan)
  results <- adonis2(equation, data = metadata, na.action = na.omit)
  coef <- results %>%
    rownames_to_column(var = "Term") %>%
    filter(Term != "Residual") %>%
    filter(Term != "Total")
  print(coef)
}
ps0.gen <- tax_glom(ps0, taxrank = "Genus", NArm = TRUE)
#Rename taxa with genus names
genus.names <- make.names(tax_table(ps0.gen)[,'Genus'], unique = TRUE)
taxa_names(ps0.gen) <- genus.names

ps0.gen_comp <- ps0 %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Genus")
  
#regression analysis @ genus level
lm_mal <- permanova_func(equation = dist ~ mal.type, data = ps0.gen_comp)

#rm(list = ls()[grep("^lm", ls())])

library(microViz)
c <- ps0.gen %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Genus") %>%
  dist_calc("bray") %>%
  ord_calc(method = "PCoA") %>%
  ord_plot(color = "mal.type", plot_taxa = 1:10, size = 5, expand = TRUE,
           tax_lab_style = tax_lab_style(type = "text", size = 4, check_overlap = TRUE)) +
  scale_colour_manual(values = colors) +
  labs(color = "Malnutrition Class") +
  theme_bw() +
  #annotate("text", x = 2, y = -2.5, size = 3,
           #label = paste("PERMANOVA Test: R2 = 0.075, p = 0.001")) +
  scale_colour_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") +
  labs(subtitle = "PERMANOVA Test: R2 = 0.065, p = 0.001")
ggsave("Output/Combined/BetaDiv/BetaDiv.png", plot = c, dpi = 600, device = "png", width = 8, height = 8, units = "in")
```

Combine plots
```{r}
library(ggpubr)

ggarrange(a, ggarrange(b,c, nrow = 2, labels = c("B.", "C.")),
          nrow = 1, labels = c("A."))
ggsave("Output/Combined/combined_plot.png", plot = last_plot(), dpi = 600, device = "png", 
       width = 12, height = 8, units = "in")
```

Differential Abundance of microbes
1. Stunting vs SAM

Phylum
```{r}
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Phylum") %>%
  taxatree_models(type = "lm", 
                  rank = "Phylum",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get()%>% filter(p.adj.BY.rank < 0.05)
  print(lm_stats2)
}

lm_laz <- lm_mod_func(var = "mal.type", data = ps0)
#Calculate mean abundance and prevalence for each feature
prop_prev_data <- ps0 %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Phylum") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename("taxon" ="OTU")
lm_stat3 <- left_join(lm_laz, prop_prev_data, by = "taxon")
write.csv(lm_stat3 %>% filter(p.adj.BY.rank < 0.05), "Output/Combined/Abund_lm_models/lm_SamType_phy.csv")

#plot the  significant taxa:
plot_data <- ps0 %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Phylum") %>%
  ps_get() %>%
  ps_otu2samdat(c("Actinobacteriota", "Fusobacteriota")) %>%
  samdat_tbl()

plot_data %>% 
  pivot_longer(cols = c(Actinobacteriota,Fusobacteriota), 
               names_to = "vars", values_to = "val") %>%
  filter(!is.na(val))%>%
  filter(val != 0) %>%
ggplot(aes(x = mal.type, y = val)) +
  geom_boxplot(colour = "grey35") +
  geom_jitter(width = 0.2, alpha = 0.5) +
  theme_bw() +
  facet_wrap(~vars, scales = "free_y") +
  labs(x = "", y = "Relative Abundance")
ggsave("Output/Combined/Abund_lm_models/lm_sig_phy.png", plot = last_plot(), dpi = 600, device = "png", 
       width = 6, height = 4, units = "in")
```

class
```{r}
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Class") %>%
  taxatree_models(type = "lm", 
                  rank = "Class",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get()%>% filter(p.adj.BY.rank < 0.05)
  print(lm_stats2)
}

lm_laz <- lm_mod_func(var = "mal.type", data = ps0)
#Calculate mean abundance and prevalence for each feature
prop_prev_data <- ps0 %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Class") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename("taxon" ="OTU")
lm_stat3 <- left_join(lm_laz, prop_prev_data, by = "taxon")
write.csv(lm_stat3 %>% filter(p.adj.BY.rank < 0.05), "Output/Combined/Abund_lm_models/lm_SamType_class.csv")

#plot the  significant taxa:
plot_data <- ps0 %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Class") %>%
  ps_get() %>%
  ps_otu2samdat(c("Actinobacteria", "Coriobacteriia", "Negativicutes", "Clostridia", "Fusobacteriia")) %>%
  samdat_tbl()

plot_data %>% 
  pivot_longer(cols = c(Actinobacteria, Coriobacteriia, Negativicutes, Clostridia, Fusobacteriia), 
               names_to = "vars", values_to = "val") %>%
  filter(!is.na(val))%>%
  filter(val != 0) %>%
ggplot(aes(x = mal.type, y = val)) +
  geom_boxplot(colour = "grey35") +
  geom_jitter(width = 0.2, alpha = 0.5) +
  theme_bw() +
  facet_wrap(~vars, scales = "free_y") +
  labs(x = "", y = "Relative Abundance")
ggsave("Output/Combined/Abund_lm_models/lm_sig_class.png", plot = last_plot(), dpi = 600, device = "png", 
       width = 6, height = 6, units = "in")
```

Order
```{r}
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Order") %>%
  taxatree_models(type = "lm", 
                  rank = "Order",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get()%>% filter(p.adj.BY.rank < 0.05)
  print(lm_stats2)
}

lm_laz <- lm_mod_func(var = "mal.type", data = ps0)
#Calculate mean abundance and prevalence for each feature
prop_prev_data <- ps0 %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Order") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename("taxon" ="OTU")
lm_stat3 <- left_join(lm_laz, prop_prev_data, by = "taxon")
write.csv(lm_stat3 %>% filter(p.adj.BY.rank < 0.05), "Output/Combined/Abund_lm_models/lm_SamType_ord.csv")

#plot the  significant taxa:
plot_data <- ps0 %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Order") %>%
  ps_get() %>%
  ps_otu2samdat(c("Actinomycetales","Corynebacteriales","Coriobacteriales","Pseudomonadales","Burkholderiales","Veillonellales-Selenomonadales","Peptostreptococcales-Tissierellales","Staphylococcales","Lachnospirales","Oscillospirales","Fusobacteriales")) %>%
  samdat_tbl()

plot_data %>% 
  pivot_longer(cols = c(Actinomycetales,Corynebacteriales,Coriobacteriales,Pseudomonadales,Burkholderiales,`Veillonellales-Selenomonadales`,`Peptostreptococcales-Tissierellales`,Staphylococcales,Lachnospirales,Oscillospirales,Fusobacteriales), 
               names_to = "vars", values_to = "val") %>%
  filter(!is.na(val))%>%
  filter(val != 0) %>%
ggplot(aes(x = mal.type, y = val)) +
  geom_boxplot(colour = "grey35") +
  geom_jitter(width = 0.2, alpha = 0.5) +
  theme_bw() +
  facet_wrap(~vars, scales = "free_y") +
  labs(x = "", y = "Relative Abundance")
ggsave("Output/Combined/Abund_lm_models/lm_sig_ord.png", plot = last_plot(), dpi = 600, device = "png", 
       width = 8, height = 4, units = "in")
```

Family
```{r}
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Family") %>%
  taxatree_models(type = "lm", 
                  rank = "Family",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get()%>% filter(p.adj.BY.rank < 0.05)
  print(lm_stats2)
}

lm_laz <- lm_mod_func(var = "mal.type", data = ps0)
#Calculate mean abundance and prevalence for each feature
prop_prev_data <- ps0 %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Family") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename("taxon" ="OTU")
lm_stat3 <- left_join(lm_laz, prop_prev_data, by = "taxon")
write.csv(lm_stat3 %>% filter(p.adj.BY.rank < 0.05), "Output/Combined/Abund_lm_models/lm_SamType_fam.csv")

#plot the  significant taxa:
plot_data <- ps0 %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Family") %>%
  ps_get() %>%
  ps_otu2samdat(c("Actinomycetaceae","Corynebacteriaceae","Atopobiaceae","Pseudomonadaceae","Burkholderiaceae","Enterobacteriaceae","Veillonellaceae","Lactobacillaceae","Gemellaceae","Carnobacteriaceae","Aerococcaceae","Anaerovoracaceae","Lachnospiraceae","Ruminococcaceae","Fusobacteriaceae")) %>%
  samdat_tbl()

plot_data %>% 
  pivot_longer(cols = c(Actinomycetaceae,Corynebacteriaceae,Atopobiaceae,Pseudomonadaceae,Burkholderiaceae,Enterobacteriaceae,Veillonellaceae,Lactobacillaceae,Gemellaceae,Carnobacteriaceae,Aerococcaceae,Anaerovoracaceae,Lachnospiraceae,Ruminococcaceae,Fusobacteriaceae), 
               names_to = "vars", values_to = "val") %>%
  filter(!is.na(val))%>%
  filter(val != 0) %>%
ggplot(aes(x = mal.type, y = val)) +
  geom_boxplot(colour = "grey35") +
  geom_jitter(width = 0.2, alpha = 0.5) +
  theme_bw() +
  facet_wrap(~vars, scales = "free_y", ncol = 5) +
  labs(x = "", y = "Relative Abundance")
ggsave("Output/Combined/Abund_lm_models/lm_sig_fam.png", plot = last_plot(), dpi = 600, device = "png", 
       width = 10, height = 6, units = "in")
```

Genus:
```{r}
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Genus") %>%
  taxatree_models(type = "lm", 
                  rank = "Genus",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get()
  print(lm_stats2)
}

lm_laz <- lm_mod_func(var = "mal.type", data = ps0)
#Calculate mean abundance and prevalence for each feature
prop_prev_data <- ps0 %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Genus") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename("taxon" ="OTU")
lm_stat3 <- left_join(lm_laz, prop_prev_data, by = "taxon")
write.csv(lm_stat3 %>% filter(p.adj.BY.rank < 0.05), "Output/Combined/Abund_lm_models/lm_SamType_gen.csv")


#plot the  significant taxa:
lm_stat4 <- lm_stat3 %>% filter(p.adj.BY.rank < 0.05)
plot_data <- ps0 %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Genus") %>%
  ps_get() %>%
  ps_otu2samdat(c("[Eubacterium] nodatum group", "Abiotrophia", "Actinomyces", "Atopobium", "Blautia",  "Burkholderia-Caballeronia-Paraburkholderia", "Corynebacterium", 
                  "Dolosigranulum", "Escherichia-Shigella", "Fusobacterium", "Gemella", 
                  "Granulicatella", "Johnsonella", "Klebsiella", "Lachnoanaerobaculum", 
                  "Lachnospiraceae Family", "Lactobacillus", "Limosilactobacillus", 
                  "Ligilactobacillus", "Mogibacterium", "Neisseria", "Pseudomonas", 
                  "Ralstonia", "Veillonella")) %>%
  samdat_tbl()

plot_data %>% 
  pivot_longer(cols = c(`[Eubacterium] nodatum group`, Abiotrophia, Actinomyces, Atopobium, Blautia,
                        `Burkholderia-Caballeronia-Paraburkholderia`, Corynebacterium, Dolosigranulum, 
                        `Escherichia-Shigella`, Fusobacterium, Gemella, Granulicatella, Johnsonella,
                        Klebsiella, Lachnoanaerobaculum, `Lachnospiraceae Family`, Lactobacillus, 
                        Limosilactobacillus, Ligilactobacillus, Mogibacterium, Neisseria, Pseudomonas, 
                        Ralstonia, Veillonella), 
               names_to = "vars", values_to = "val") %>%
  filter(!is.na(val))%>%
  filter(val != 0)%>%
ggplot(aes(x = mal.type, y = val)) +
  geom_boxplot(colour = "grey35") +
  geom_jitter(width = 0.2, alpha = 0.5) +
  theme_bw() +
  facet_wrap(~vars, scales = "free_y", ncol = 6) +
  labs(x = "", y = "Relative Abundance")
ggsave("Output/Combined/Abund_lm_models/lm_sig.png", plot = last_plot(), dpi = 600, device = "png", 
       width = 15, height = 6, units = "in")

# Generate volcano plots
ggplot(lm_stat3, aes(x = estimate, y = -log10(p.adj.BY.rank), size = avg_abundance)) +
#ggplot(lm_stat3, aes(x = estimate, y = -log10(p.adj.BY.rank), color = prevalence, size = avg_abundance)) +
  geom_point() +
  geom_vline(aes(xintercept = 0),linetype = "dashed",linewidth = 1.5, color = "grey") + # Add vertical line at x=0 to show no change
  geom_hline(aes(yintercept = -log10(0.05)),linetype = "dashed",linewidth = 1.5,color = "grey") + # Add horizontal line at the significance level
  ggrepel::geom_text_repel(aes(label = ifelse(p.adj.BY.rank < 0.05, as.character(taxon),'')),
                           size = 3.5,
                           box.padding = 0.35,
                           point.padding = 0.5) +  # Add labels for significant features
  scale_shape_manual(values = c(16, 17)) +
  labs(title = "Stunting vs SAM (Reference)",
       x = "Estimate",
       y = "-log10(p-value)",
       color = "Prevalence",
       size = "Mean Abundance") +
  theme_bw() +
  theme(plot.title.position = "plot",
        plot.title = element_text(hjust = 0.5, size = 12),
        panel.grid.major = element_line(color = "grey", linetype = "dashed"),
        panel.grid.minor = element_line(color = "grey", linetype = "dotted"),
        legend.position = "bottom",
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 14)) +
  #scale_color_gradientn(colors = c("white", "#7FB695", "#006D2C")) +  # Use a gradient color scale for prevalence
  scale_size_continuous(range = c(3, 7))  # Set the size range for mean abundance
ggsave("Output/Combined/Abund_lm_models/VolcaoPlot_maltype.png", plot = last_plot(), dpi = 600, device = "png", width = 12, height = 8, units = "in")

```

2. Pathways - do not run
```{r}
library(MicrobiomeStat)
library(MicrobiomeProfiler)
library(ggpicrust2)
library(readr)
library(Maaslin2)
#import data
#pathways abundance
pathway_dat <- read.delim("Output/Combined/Picrust2_Output/dir/pathways_out/path_abun_unstrat.tsv")%>%
  column_to_rownames(var = "pathway")
names(pathway_dat) <- substring(names(pathway_dat),2)

#metadata
metadata <- read_csv("Data/Final_Metadata.csv") %>%
  column_to_rownames(var = "SampleID")

#Get pathway descriptions and create feature.ann (pathway taxonomy)
path_df <- pathway_annotation(
  file = "Output/Combined/Picrust2_Output/dir/pathways_out/path_abun_unstrat.tsv",
  pathway = "MetaCyc",
  daa_results_df = path_df,
  ko_to_kegg = FALSE
)
#add pathway description to file
feature_ann <- path_df %>% 
  select(pathway, description) %>% 
  mutate(pathID = pathway) %>%
  column_to_rownames(var = "pathway")

#create MicrobiomeStat object
ps.obj <- list(
  feature.tab = as.matrix(pathway_dat),
  meta.dat = metadata,
  feature.ann = as.matrix(feature_ann)
)

# Generate taxa test
test.list <- generate_taxa_test_single(
    data.obj = ps.obj,
    time.var = NULL,
    t.level = NULL,
    group.var = "mal.type",
    feature.dat.type = "count",
    feature.level = c("description"),
    prev.filter = 0.1,
    abund.filter = 0.0001
)

# Generate volcano plots
volcano_plots <- generate_taxa_volcano_single(
    data.obj = ps.obj,
    group.var = "mal.type",
    test.list = test.list,
    feature.sig.level = 0.05,
    feature.mt.method = "none"
)

v1 <- volcano_plots[["description"]][["Stunting vs SAM (Reference)"]] +
  theme(legend.position = "right")
ggsave(plot = v1, filename = "Output/Combined/Picrust2_Output/pathwayplot_SAMTYPE.png", dpi = 600)
```

3. Clinical features

```{r}
#1. Genus
library(tidyverse)
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Genus") %>%
  taxatree_models(type = "lm", 
                  rank = "Genus",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get() %>% filter(`p.adj.BY.rank` < 0.05) %>% filter(term == var)
  #get prevalence of taxa
  prop_prev_data <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Genus") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename('taxon'= 'OTU')
  lm_stat3 <- left_join(lm_stats2, prop_prev_data, by = "taxon")
  print(lm_stat3)
}
library(metagMisc)
ps0_st <- ps0 %>%
  ps_filter(mal.type == "Stunting")
ps0_sam <- ps0 %>%
  ps_filter(mal.type == "SAM")
#a) Stunting
lm_age <- lm_mod_func(var = "AgeMonths_endo", data = ps0_st)
lm_laz <- lm_mod_func(var = "LAZ_endo", data = ps0_st)
lm_waz <- lm_mod_func(var = "WAZ_endo", data = ps0_st)
lm_whz <- lm_mod_func(var = "WHZ_endo", data = ps0_st)
lm_sex <- lm_mod_func(var = "Sex", data = ps0_st)
lm_gast <- lm_mod_func(var =  "GastricPh_endo", data = ps0_st)
lm_glp2 <- lm_mod_func(var =  "GLP.2_endo", data = ps0_st)
lm_fabp <- lm_mod_func(var =  "I.FABP_endo", data = ps0_st)
lm_lps <- lm_mod_func(var = "LPS_endo", data = ps0_st)
lm_lbp<- lm_mod_func(var =  "LBP_endo", data = ps0_st)
lm_scd14 <- lm_mod_func(var =  "sCD14_endo", data = ps0_st)
lm_vh <- lm_mod_func(var =  "VH", data = ps0_st)
lm_cd <- lm_mod_func(var =  "CD", data = ps0_st)
lm_esa <- lm_mod_func(var =  "ESA", data = ps0_st)
lm_hiv <- lm_mod_func(var =  "hiv_char", data = ps0_st)

df_list <- list(lm_age, lm_laz, lm_waz, lm_whz, lm_sex, lm_gast, lm_glp2, lm_fabp, lm_lps, lm_lbp, lm_scd14, lm_vh ,lm_cd,
                lm_esa, lm_hiv)
lm_biomarkers <- Reduce(function(x,y) merge(x, y, all.x = TRUE, all.y = TRUE), df_list)
write.csv(lm_biomarkers, "Output/Combined/Abund_lm_models/lm_clinical_feats_stunting_gen.csv")
rm(list = ls()[grep("^lm", ls())])
#b) SAM
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Genus") %>%
  taxatree_models(type = "lm", 
                  rank = "Genus",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get() %>% filter(`p.adj.BY.rank` < 0.05) %>% filter(term == var)
  #get prevalence of taxa
  prop_prev_data <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Genus") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename('taxon'= 'OTU')
  lm_stat3 <- left_join(lm_stats2, prop_prev_data, by = "taxon")
  print(lm_stat3)
}
lm_age <- lm_mod_func(var = "AgeMonths_endo", data = ps0_sam)
lm_laz <- lm_mod_func(var = "LAZ_endo", data = ps0_sam)
lm_waz <- lm_mod_func(var = "WAZ_endo", data = ps0_sam)
lm_whz <- lm_mod_func(var = "WHZ_endo", data = ps0_sam)
lm_sex <- lm_mod_func(var = "Sex", data = ps0_sam)
lm_gast <- lm_mod_func(var =  "GastricPh_endo", data = ps0_sam)
lm_glp2 <- lm_mod_func(var =  "GLP.2_endo", data = ps0_sam)
lm_fabp <- lm_mod_func(var =  "I.FABP_endo", data = ps0_sam)
lm_lps <- lm_mod_func(var = "LPS_endo", data = ps0_sam)
lm_lbp<- lm_mod_func(var =  "LBP_endo", data = ps0_sam)
lm_scd14 <- lm_mod_func(var =  "sCD14_endo", data = ps0_sam)
lm_vh <- lm_mod_func(var =  "VH", data = ps0_sam)
lm_cd <- lm_mod_func(var =  "CD", data = ps0_sam)
lm_esa <- lm_mod_func(var =  "ESA", data = ps0_sam)
lm_hiv <- lm_mod_func(var =  "hiv_char", data = ps0_sam)

df_list <- list(lm_age, lm_laz, lm_waz, lm_whz, lm_sex, lm_gast, lm_glp2, lm_fabp, lm_lps, lm_lbp, lm_scd14)
lm_biomarkers <- Reduce(function(x,y) merge(x, y, all.x = TRUE, all.y = TRUE), df_list) #nothing is significant
write.csv(lm_biomarkers, "Output/Combined/Abund_lm_models/lm_clinical_feats_sam_gen.csv")
rm(list = ls()[grep("^lm", ls())])
```

#2. Family
```{r}
library(tidyverse)
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Family") %>%
  taxatree_models(type = "lm", 
                  rank = "Family",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get() %>% filter(`p.adj.BY.rank` < 0.05) %>% filter(term == var)
  #get prevalence of taxa
  prop_prev_data <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Family") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename('taxon'= 'OTU')
  lm_stat3 <- left_join(lm_stats2, prop_prev_data, by = "taxon")
  print(lm_stat3)
}
library(metagMisc)
#a) Stunting
lm_age <- lm_mod_func(var = "AgeMonths_endo", data = ps0_st)
lm_laz <- lm_mod_func(var = "LAZ_endo", data = ps0_st)
lm_waz <- lm_mod_func(var = "WAZ_endo", data = ps0_st)
lm_whz <- lm_mod_func(var = "WHZ_endo", data = ps0_st)
lm_sex <- lm_mod_func(var = "Sex", data = ps0_st)
lm_gast <- lm_mod_func(var =  "GastricPh_endo", data = ps0_st)
lm_glp2 <- lm_mod_func(var =  "GLP.2_endo", data = ps0_st)
lm_fabp <- lm_mod_func(var =  "I.FABP_endo", data = ps0_st)
lm_lps <- lm_mod_func(var = "LPS_endo", data = ps0_st)
lm_lbp<- lm_mod_func(var =  "LBP_endo", data = ps0_st)
lm_scd14 <- lm_mod_func(var =  "sCD14_endo", data = ps0_st)
lm_vh <- lm_mod_func(var =  "VH", data = ps0_st)
lm_cd <- lm_mod_func(var =  "CD", data = ps0_st)
lm_esa <- lm_mod_func(var =  "ESA", data = ps0_st)
lm_hiv <- lm_mod_func(var =  "hiv_char", data = ps0_st)

df_list <- list(lm_age, lm_laz, lm_waz, lm_whz, lm_sex, lm_gast, lm_glp2, lm_fabp, lm_lps, lm_lbp, lm_scd14, lm_vh ,lm_cd,
                lm_esa, lm_hiv)
lm_biomarkers <- Reduce(function(x,y) merge(x, y, all.x = TRUE, all.y = TRUE), df_list)
write.csv(lm_biomarkers, "Output/Combined/Abund_lm_models/lm_clinical_feats_stunting_fam.csv")
rm(list = ls()[grep("^lm", ls())])
#b) SAM
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Family") %>%
  taxatree_models(type = "lm", 
                  rank = "Family",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get() %>% filter(`p.adj.BY.rank` < 0.05) %>% filter(term == var)
  #get prevalence of taxa
  prop_prev_data <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Family") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename('taxon'= 'OTU')
  lm_stat3 <- left_join(lm_stats2, prop_prev_data, by = "taxon")
  print(lm_stat3)
}
lm_age <- lm_mod_func(var = "AgeMonths_endo", data = ps0_sam)
lm_laz <- lm_mod_func(var = "LAZ_endo", data = ps0_sam)
lm_waz <- lm_mod_func(var = "WAZ_endo", data = ps0_sam)
lm_whz <- lm_mod_func(var = "WHZ_endo", data = ps0_sam)
lm_sex <- lm_mod_func(var = "Sex", data = ps0_sam)
lm_gast <- lm_mod_func(var =  "GastricPh_endo", data = ps0_sam)
lm_glp2 <- lm_mod_func(var =  "GLP.2_endo", data = ps0_sam)
lm_fabp <- lm_mod_func(var =  "I.FABP_endo", data = ps0_sam)
lm_lps <- lm_mod_func(var = "LPS_endo", data = ps0_sam)
lm_lbp<- lm_mod_func(var =  "LBP_endo", data = ps0_sam)
lm_scd14 <- lm_mod_func(var =  "sCD14_endo", data = ps0_sam)
lm_vh <- lm_mod_func(var =  "VH", data = ps0_sam)
lm_cd <- lm_mod_func(var =  "CD", data = ps0_sam)
lm_esa <- lm_mod_func(var =  "ESA", data = ps0_sam)
lm_hiv <- lm_mod_func(var =  "hiv_char", data = ps0_sam)

df_list <- list(lm_age, lm_laz, lm_waz, lm_whz, lm_sex, lm_gast, lm_glp2, lm_fabp, lm_lps, lm_lbp, lm_scd14)
lm_biomarkers <- Reduce(function(x,y) merge(x, y, all.x = TRUE, all.y = TRUE), df_list) #nothing is significant
write.csv(lm_biomarkers, "Output/Combined/Abund_lm_models/lm_clinical_feats_sam_fam.csv")
rm(list = ls()[grep("^lm", ls())])
``` 

#3. Class
```{r}
library(tidyverse)
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Class") %>%
  taxatree_models(type = "lm", 
                  rank = "Class",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get() %>% filter(`p.adj.BY.rank` < 0.05) %>% filter(term == var)
  #get prevalence of taxa
  prop_prev_data <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Class") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename('taxon'= 'OTU')
  lm_stat3 <- left_join(lm_stats2, prop_prev_data, by = "taxon")
  print(lm_stat3)
}
library(metagMisc)
#a) Stunting
lm_age <- lm_mod_func(var = "AgeMonths_endo", data = ps0_st)
lm_laz <- lm_mod_func(var = "LAZ_endo", data = ps0_st)
lm_waz <- lm_mod_func(var = "WAZ_endo", data = ps0_st)
lm_whz <- lm_mod_func(var = "WHZ_endo", data = ps0_st)
lm_sex <- lm_mod_func(var = "Sex", data = ps0_st)
lm_gast <- lm_mod_func(var =  "GastricPh_endo", data = ps0_st)
lm_glp2 <- lm_mod_func(var =  "GLP.2_endo", data = ps0_st)
lm_fabp <- lm_mod_func(var =  "I.FABP_endo", data = ps0_st)
lm_lps <- lm_mod_func(var = "LPS_endo", data = ps0_st)
lm_lbp<- lm_mod_func(var =  "LBP_endo", data = ps0_st)
lm_scd14 <- lm_mod_func(var =  "sCD14_endo", data = ps0_st)
lm_vh <- lm_mod_func(var =  "VH", data = ps0_st)
lm_cd <- lm_mod_func(var =  "CD", data = ps0_st)
lm_esa <- lm_mod_func(var =  "ESA", data = ps0_st)
lm_hiv <- lm_mod_func(var =  "hiv_char", data = ps0_st)

df_list <- list(lm_age, lm_laz, lm_waz, lm_whz, lm_sex, lm_gast, lm_glp2, lm_fabp, lm_lps, lm_lbp, lm_scd14, lm_vh ,lm_cd,
                lm_esa, lm_hiv)
lm_biomarkers <- Reduce(function(x,y) merge(x, y, all.x = TRUE, all.y = TRUE), df_list)
write.csv(lm_biomarkers, "Output/Combined/Abund_lm_models/lm_clinical_feats_stunting_clas.csv")
rm(list = ls()[grep("^lm", ls())])
#b) SAM
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Class") %>%
  taxatree_models(type = "lm", 
                  rank = "Class",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get() %>% filter(`p.adj.BY.rank` < 0.05) %>% filter(term == var)
  #get prevalence of taxa
  prop_prev_data <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Class") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename('taxon'= 'OTU')
  lm_stat3 <- left_join(lm_stats2, prop_prev_data, by = "taxon")
  print(lm_stat3)
}

lm_age <- lm_mod_func(var = "AgeMonths_endo", data = ps0_sam)
lm_laz <- lm_mod_func(var = "LAZ_endo", data = ps0_sam)
lm_waz <- lm_mod_func(var = "WAZ_endo", data = ps0_sam)
lm_whz <- lm_mod_func(var = "WHZ_endo", data = ps0_sam)
lm_sex <- lm_mod_func(var = "Sex", data = ps0_sam)
lm_gast <- lm_mod_func(var =  "GastricPh_endo", data = ps0_sam)
lm_glp2 <- lm_mod_func(var =  "GLP.2_endo", data = ps0_sam)
lm_fabp <- lm_mod_func(var =  "I.FABP_endo", data = ps0_sam)
lm_lps <- lm_mod_func(var = "LPS_endo", data = ps0_sam)
lm_lbp<- lm_mod_func(var =  "LBP_endo", data = ps0_sam)
lm_scd14 <- lm_mod_func(var =  "sCD14_endo", data = ps0_sam)
lm_vh <- lm_mod_func(var =  "VH", data = ps0_sam)
lm_cd <- lm_mod_func(var =  "CD", data = ps0_sam)
lm_esa <- lm_mod_func(var =  "ESA", data = ps0_sam)
lm_hiv <- lm_mod_func(var =  "hiv_char", data = ps0_sam)

df_list <- list(lm_age, lm_laz, lm_waz, lm_whz, lm_sex, lm_gast, lm_glp2, lm_fabp, lm_lps, lm_lbp, lm_scd14)
lm_biomarkers <- Reduce(function(x,y) merge(x, y, all.x = TRUE, all.y = TRUE), df_list) #nothing is significant
write.csv(lm_biomarkers, "Output/Combined/Abund_lm_models/lm_clinical_feats_sam_clas.csv")
rm(list = ls()[grep("^lm", ls())])
```

#4. Order
```{r}
library(tidyverse)
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Order") %>%
  taxatree_models(type = "lm", 
                  rank = "Order",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get() %>% filter(`p.adj.BY.rank` < 0.05) %>% filter(term == var)
  #get prevalence of taxa
  prop_prev_data <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Order") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename('taxon'= 'OTU')
  lm_stat3 <- left_join(lm_stats2, prop_prev_data, by = "taxon")
  print(lm_stat3)
}
library(metagMisc)
#a) Stunting
lm_age <- lm_mod_func(var = "AgeMonths_endo", data = ps0_st)
lm_laz <- lm_mod_func(var = "LAZ_endo", data = ps0_st)
lm_waz <- lm_mod_func(var = "WAZ_endo", data = ps0_st)
lm_whz <- lm_mod_func(var = "WHZ_endo", data = ps0_st)
lm_sex <- lm_mod_func(var = "Sex", data = ps0_st)
lm_gast <- lm_mod_func(var =  "GastricPh_endo", data = ps0_st)
lm_glp2 <- lm_mod_func(var =  "GLP.2_endo", data = ps0_st)
lm_fabp <- lm_mod_func(var =  "I.FABP_endo", data = ps0_st)
lm_lps <- lm_mod_func(var = "LPS_endo", data = ps0_st)
lm_lbp<- lm_mod_func(var =  "LBP_endo", data = ps0_st)
lm_scd14 <- lm_mod_func(var =  "sCD14_endo", data = ps0_st)
lm_vh <- lm_mod_func(var =  "VH", data = ps0_st)
lm_cd <- lm_mod_func(var =  "CD", data = ps0_st)
lm_esa <- lm_mod_func(var =  "ESA", data = ps0_st)
lm_hiv <- lm_mod_func(var =  "hiv_char", data = ps0_st)

df_list <- list(lm_age, lm_laz, lm_waz, lm_whz, lm_sex, lm_gast, lm_glp2, lm_fabp, lm_lps, lm_lbp, lm_scd14, lm_vh ,lm_cd,
                lm_esa, lm_hiv)
lm_biomarkers <- Reduce(function(x,y) merge(x, y, all.x = TRUE, all.y = TRUE), df_list)
write.csv(lm_biomarkers, "Output/Combined/Abund_lm_models/lm_clinical_feats_stunting_ord.csv")
rm(list = ls()[grep("^lm", ls())])
#b) SAM
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Order") %>%
  taxatree_models(type = "lm", 
                  rank = "Order",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get() %>% filter(`p.adj.BY.rank` < 0.05) %>% filter(term == var)
  #get prevalence of taxa
  prop_prev_data <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Order") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename('taxon'= 'OTU')
  lm_stat3 <- left_join(lm_stats2, prop_prev_data, by = "taxon")
  print(lm_stat3)
}
lm_age <- lm_mod_func(var = "AgeMonths_endo", data = ps0_sam)
lm_laz <- lm_mod_func(var = "LAZ_endo", data = ps0_sam)
lm_waz <- lm_mod_func(var = "WAZ_endo", data = ps0_sam)
lm_whz <- lm_mod_func(var = "WHZ_endo", data = ps0_sam)
lm_sex <- lm_mod_func(var = "Sex", data = ps0_sam)
lm_gast <- lm_mod_func(var =  "GastricPh_endo", data = ps0_sam)
lm_glp2 <- lm_mod_func(var =  "GLP.2_endo", data = ps0_sam)
lm_fabp <- lm_mod_func(var =  "I.FABP_endo", data = ps0_sam)
lm_lps <- lm_mod_func(var = "LPS_endo", data = ps0_sam)
lm_lbp<- lm_mod_func(var =  "LBP_endo", data = ps0_sam)
lm_scd14 <- lm_mod_func(var =  "sCD14_endo", data = ps0_sam)
lm_vh <- lm_mod_func(var =  "VH", data = ps0_sam)
lm_cd <- lm_mod_func(var =  "CD", data = ps0_sam)
lm_esa <- lm_mod_func(var =  "ESA", data = ps0_sam)
lm_hiv <- lm_mod_func(var =  "hiv_char", data = ps0_sam)

df_list <- list(lm_age, lm_laz, lm_waz, lm_whz, lm_sex, lm_gast, lm_glp2, lm_fabp, lm_lps, lm_lbp, lm_scd14)
lm_biomarkers <- Reduce(function(x,y) merge(x, y, all.x = TRUE, all.y = TRUE), df_list) #nothing is significant
write.csv(lm_biomarkers, "Output/Combined/Abund_lm_models/lm_clinical_feats_sam_ord.csv")
rm(list = ls()[grep("^lm", ls())])
```

#5. Phylum
```{r}
library(tidyverse)
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Phylum") %>%
  taxatree_models(type = "lm", 
                  rank = "Phylum",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get() %>% filter(`p.adj.BY.rank` < 0.05) %>% filter(term == var)
  #get prevalence of taxa
  prop_prev_data <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Phylum") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename('taxon'= 'OTU')
  lm_stat3 <- left_join(lm_stats2, prop_prev_data, by = "taxon")
  print(lm_stat3)
}
library(metagMisc)
#a) Stunting
lm_age <- lm_mod_func(var = "AgeMonths_endo", data = ps0_st)
lm_laz <- lm_mod_func(var = "LAZ_endo", data = ps0_st)
lm_waz <- lm_mod_func(var = "WAZ_endo", data = ps0_st)
lm_whz <- lm_mod_func(var = "WHZ_endo", data = ps0_st)
lm_sex <- lm_mod_func(var = "Sex", data = ps0_st)
lm_gast <- lm_mod_func(var =  "GastricPh_endo", data = ps0_st)
lm_glp2 <- lm_mod_func(var =  "GLP.2_endo", data = ps0_st)
lm_fabp <- lm_mod_func(var =  "I.FABP_endo", data = ps0_st)
lm_lps <- lm_mod_func(var = "LPS_endo", data = ps0_st)
lm_lbp<- lm_mod_func(var =  "LBP_endo", data = ps0_st)
lm_scd14 <- lm_mod_func(var =  "sCD14_endo", data = ps0_st)
lm_vh <- lm_mod_func(var =  "VH", data = ps0_st)
lm_cd <- lm_mod_func(var =  "CD", data = ps0_st)
lm_esa <- lm_mod_func(var =  "ESA", data = ps0_st)
lm_hiv <- lm_mod_func(var =  "hiv_char", data = ps0_st)

df_list <- list(lm_age, lm_laz, lm_waz, lm_whz, lm_sex, lm_gast, lm_glp2, lm_fabp, lm_lps, lm_lbp, lm_scd14, lm_vh ,lm_cd,
                lm_esa, lm_hiv)
lm_biomarkers <- Reduce(function(x,y) merge(x, y, all.x = TRUE, all.y = TRUE), df_list)
write.csv(lm_biomarkers, "Output/Combined/Abund_lm_models/lm_clinical_feats_stunting_phy.csv")
rm(list = ls()[grep("^lm", ls())])
#b) SAM
lm_mod_func = function(var,data){
  require(microViz)
  mod_lm <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Phylum") %>%
  taxatree_models(type = "lm", 
                  rank = "Phylum",
                  trans = "log2", 
                  trans_args = list(zero_replace = "halfmin"),
                  variables = c(var))
  lm_stats <- taxatree_models2stats(mod_lm)
  lm_stats <- taxatree_stats_p_adjust(data = lm_stats, method = "BY", grouping = "rank")
  lm_stats2 <- lm_stats %>% taxatree_stats_get() %>% filter(`p.adj.BY.rank` < 0.05) %>% filter(term == var)
  #get prevalence of taxa
  prop_prev_data <- data %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Phylum") %>%
  ps_melt() %>%
  group_by(OTU) %>%
  summarise(avg_abundance = mean(Abundance),
            prevalence = sum(Abundance > 0) / dplyr::n()) %>%
  rename('taxon'= 'OTU')
  lm_stat3 <- left_join(lm_stats2, prop_prev_data, by = "taxon")
  print(lm_stat3)
}
lm_age <- lm_mod_func(var = "AgeMonths_endo", data = ps0_sam)
lm_laz <- lm_mod_func(var = "LAZ_endo", data = ps0_sam)
lm_waz <- lm_mod_func(var = "WAZ_endo", data = ps0_sam)
lm_whz <- lm_mod_func(var = "WHZ_endo", data = ps0_sam)
lm_sex <- lm_mod_func(var = "Sex", data = ps0_sam)
lm_gast <- lm_mod_func(var =  "GastricPh_endo", data = ps0_sam)
lm_glp2 <- lm_mod_func(var =  "GLP.2_endo", data = ps0_sam)
lm_fabp <- lm_mod_func(var =  "I.FABP_endo", data = ps0_sam)
lm_lps <- lm_mod_func(var = "LPS_endo", data = ps0_sam)
lm_lbp<- lm_mod_func(var =  "LBP_endo", data = ps0_sam)
lm_scd14 <- lm_mod_func(var =  "sCD14_endo", data = ps0_sam)
lm_vh <- lm_mod_func(var =  "VH", data = ps0_sam)
lm_cd <- lm_mod_func(var =  "CD", data = ps0_sam)
lm_esa <- lm_mod_func(var =  "ESA", data = ps0_sam)
lm_hiv <- lm_mod_func(var =  "hiv_char", data = ps0_sam)

df_list <- list(lm_age, lm_laz, lm_waz, lm_whz, lm_sex, lm_gast, lm_glp2, lm_fabp, lm_lps, lm_lbp, lm_scd14)
lm_biomarkers <- Reduce(function(x,y) merge(x, y, all.x = TRUE, all.y = TRUE), df_list) #nothing is significant
write.csv(lm_biomarkers, "Output/Combined/Abund_lm_models/lm_clinical_feats_sam_phy.csv")
rm(list = ls()[grep("^lm", ls())])
```

plot significant associations in stunted children
```{r}
#Age is positively associated with increased alpha diversity in stunted children
#Alpha diversity
a <- add2 %>%
  filter(mal.type == "Stunting") %>%
  rename("AgeMonths_endo" = "Age") %>%
  filter(!is.na(Age)) %>%
  ggplot(aes(x = Age,  y = PD)) +
  geom_point() +
  labs(y = "Faith's PD",
       x = "Age (Months)",
       subtitle = "β = 0.15, p = 0.03") +
  geom_smooth(method = "lm") +
  theme_classic2()
#Abiotrophia abundance
b <- ps0_st %>%
  tax_fix() %>%
  tax_transform("compositional", rank = "Genus") %>%
  #tax_transform("log2", zero_replace = "halfmin", chain = TRUE) %>%
  ps_get() %>%
  ps_otu2samdat(c("Abiotrophia")) %>%
  samdat_tbl() %>% 
  ggplot(aes(x = AgeMonths_endo, y = Abiotrophia)) +
  geom_point(colour = "grey35") +
  geom_jitter(width = 0.2, alpha = 0.5) +
  theme_classic2() +
  labs(x = "Age (Months)",
       subtitle = "β = 0.40, p = 0.002, Prevalence = 0.91") +
  geom_smooth(method = "lm")

library(ggpubr)
ggarrange(a, b, ncol = 2, labels = c("A", "B"))
ggsave("Output/Combined/Age_assocs.png", plot = last_plot(), dpi = 600, device = "png", width = 8, height = 4, units = "in")

```

#DONE

